plugins {
    id 'net.fabricmc.fabric-loom' version "${loom_version}"
    id 'io.github.ladysnake.chenille' version "${chenille_version}"
}

version = project.mod_version
group = project.maven_group

chenille {
    customLicense = rootProject.file("LICENSE")
    github = new URL("https://github.com/doctor4t/Mariposa")
    javaVersion = 25
    configurePublishing {
        withLadysnakeMaven()
        withGithubRelease()
        withModrinthRelease()
    }
}

repositories {
    maven {
        name = "terrablender"
        url = "https://maven.minecraftforge.net/"
    }
}

fabricApi {
    configureDataGeneration() {
        client = true
        modId = project.archives_base_name
    }
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${minecraft_version}"
    implementation "net.fabricmc:fabric-loader:${loader_version}"

    // Libraries
    implementation "net.fabricmc.fabric-api:fabric-api:${fabric_version}"
    implementation "com.github.glitchfiend:TerraBlender-fabric:${terrablender_version}"
}

processResources {
    def version = project.version
    inputs.property "version", version

    filesMatching("fabric.mod.json") {
        expand "version": version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 25
}

java {
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    def projectName = project.name
    inputs.property "projectName", projectName

    from("LICENSE") {
        rename { "${it}_$projectName"}
    }
}